### ISSUE TITLE
What is the use of the CR3 forms in the application?

### ISSUE THREAD

**Issue by WrenVin** [cityofaustin/atd-vz-data#1354]
Hi, 
I see that you guys are using the TxDOT CRIS database entries in this application, but from the readme I am struggling to understand how atd-cr3-api fits in. Do the CR3 files supplement a part of the CRIS database that's missing? 

One more question, how do you guys narrow the data to be specific to austin? Do you just look at the lon/lat and see where they fall?

Thanks, I appreciate your time on this

**Comment by frankhereford** [comment]
@WrenVin, thank you for opening this issue. These are good questions. Because our team tracks issues in another place, I apologize for the delay in getting back to you. I'm going to try to more actively monitor this space. 🙏 

CR3 files are PDFs of the report submitted by officers when they respond to a crash. When everything is working as intended, the data contained in the PDFs matches the tabular data we have received from CRIS, which we parse into a relational database. This parsed data is what drives the editor and viewer web applications. The PDFs act as an effective check that the data presented in the web applications is correct and up to date.

This is another great question about how we narrow the scope of our data. You won't find any indication of this in the code base, which is unfortunate. The whole data system hinges on data we receive from TxDOT, a state reporting agency. The mechanism which TxDOT uses to distribute data is based on a recurring query that we establish with them through their website. When the query is being set up, there are a number of criteria that you can use to narrow the crashes of interest. In particular, one can specify which counties to include in the results, and we specify the three in the greater Austin area.

Thank you for your questions and interest in this data suite. Please open issues as needed, and we'll do our best to help as we're able.

**Comment by WrenVin** [comment]
Thank you @frankhereford. I am working for BikeHouston, and we are looking at building a similar data dashboard for Houston. I appreciate your feedback. If you don't mind, I had 2 more questions. 
Do you have to pay $7.50 for every CR-3 file downloaded? Our team is able to download individual files for that cost per file. 
Also, I found the CRIS Query website to narrow the scope of the data to a specific county. Do you have to manually run this query each time, or do you have a seperate script that automatically queries the CRIS database?

Thank you! 🙏
