### ISSUE TITLE
VZD: Prototype a bulk QA process for crashes w/ serious injury or fatality

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#137]
Exploring GIS-based solutions and tooling for a bulk QA process. We need a faster way to tear through the backlog of all the records (prioritizing serious injury or fatality crashes) that don't have any lat/lon values.

**Comment by mateoclarke** [comment]
@sergiogcx to send a .csv of the whole Crash Table.

**Comment by sergiogcx** [comment]
The crash data table was sent on Tuesday to Joel, let me know @frankhereford if you have not gotten it yet.


I've created a temporary table (with the same structure as the change log), with the purpose to store all failed insertions coming in from CRIS. 

The database will store records that already exist in our database, but may contain important updates. These records will be stored in JSON format for easy parsing and comparison with existing records, it should also help us with less overhead any time there is are any changes to the crashes table structure, and we can use the existing diff tool code implemented in the crash detail component.

**Comment by sergiogcx** [comment]
The way I envision the process is as follows, every new record coming in from CRIS we don't know if it is a new record, or an existing with updates or an existing without updates. So we take each and we try to insert it to Postgres.

- If it succeeds to insert it means the record did not previously exist, and there is no need to worry. 

- If it fails it means the primary key (the crash_id) already exists, and therefore we need to be careful, so that record is either exactly the same as the existing one, or it contains important updates, so it should be stored in the `change_pending` table. This allows us to list them for the user, and let the user check the differences (or lack thereof) and make a decision to incorporate the incoming record, or to discard it:

![Scrap P1 (1).png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/a96f6ff7-24d5-42ce-b870-cc181d01e3d8)

**Comment by sergiogcx** [comment]
To list the crashes, we run a SQL query and the user would click on one of them and see a dialog with a difftool, and we just have to determine how we want to implement the UI:

![Scrap P2 (1).png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/40b85ab5-6d40-4e44-b507-8f719552fc7c)

![Scrap P3 (1).png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/61ae5011-fd54-4383-b9ab-ffb248cb5f18)

**Comment by mateoclarke** [comment]
@sergiogcx, these are all really good thoughts and documentation. But... I think we created this issue for @frankhereford to think about and work on GIS-based solutions and tooling for a bulk QA process. A faster way to tear through the backlog of all the records (prioritizing serious injury or fatality crashes) that don't have any lat/lon values.

The process you're outlining sounds more like the process for consuming new data from CRIS that conflicts with existing CRIS data. Which is a different QA process than the one @frankhereford is exploring. Can you move your comments to this issue? And rename that issue if necessary?
https://github.com/cityofaustin/atd-vz-data/issues/83

**Comment by JaceDeloney** [comment]
Closing this as we have come up with a different solution
