### ISSUE TITLE
VZE: Locations Index table, standardize location names 

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#176]
Names of the locations sometimes have the north/south street first, other times, the east/west is first. Having a consistent naming pattern will help and was requested by LL.

**Comment by sergiogcx** [comment]
I am having trouble thinking of ways to automate this, I am starting to think that for now this will have to be done in the front end, or at least whoever makes the intersections map.

Otherwise, to automate I would need some kind of reference, then identify the two (or more) streets in that intersection and then determine the order at which they need to be placed in text format.

Otherwise, I am thinking we can set up an additional boolean column that indicates whether the location record address has been QA'd and verified by a human? We can show in a page a list of all locations that have not yet been verified?

**Comment by sergiogcx** [comment]
Or rather than a boolean column, we can add a status number:

0 - Not Q/A'd
1 - Street name verified
2- Geography verified
...(n - etc)

**Comment by mateoclarke** [comment]
Need @johnclary 's input here but I think this happens 1 or 2 ways:

1. manual, we make Location names editable and establish a standard for manually updating the Location names. using your status number idea.

2. with GIS magic if we want to standardize on cardinal directions. OR, we think about other ways to Location street names. Could it be Alphabetical? (ex: Elm @ Pecan). Or numbered streets first (12th @ Chicon)? Or could we use other attributes to order the names ([ASMP street rating](https://github.com/cityofaustin/atd-vz-data/issues/176)). Either way, it sounds like we need more definition from Lewis or John on what they're trying to get out of intersection name standardization

**Comment by sergiogcx** [comment]
Very well, for the time being the intersection names will be sorted out alphabetically, so basically `Chicon @ 12th` would become `12th @ Chicon`, this process will be automatic and enforced through the trigger in the locations table `atd_txdot_location_audit_log`.

This script has been tested and all records updated

**Comment by sergiogcx** [comment]
![Screen Shot 2019-09-30 at 10.17.26 AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/f2a26d3f-cfef-4226-9d31-32f7bb65580d)

**Comment by sergiogcx** [comment]
This issue is part of epic #195, closing.
