### ISSUE TITLE
VZE: Add summary counts as table columns to Locations Index page

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#244]
- total crashes
- total fatal
- total serious
- total comprehensive cost

(all should be sortable)

**Comment by sergiogcx** [comment]
Realizing now that we will need at last two new features and one bug fix for the abstraction library:

![Screen Shot 2019-10-09 at 12.25.50 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/7c5aa9d0-0d98-4097-a2f8-b77a5979f88b)

So we can show the data, but we cannot sort since the library generates the wrong syntax for nested fields (the counts), so we will need to change the library to handle those correctly.

Secondly, we also need two features:
1. Handle default values (in case there is no data)
2. Handle formats (e.g., currency formats, decimals, integer, booleans, etc)

**Comment by sergiogcx** [comment]
Currently waiting on @mddilley 's changes to the abstract library to be merged to master, so I can start working on this. Mike is also waiting on @mateoclarke for PR approval
