### ISSUE TITLE
VZE Bug: Crashes table sorting breaks when switching between columns sorted by

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-vz-data#266]
In the Crashes table (using `<GridTable />` and the gql abstract), the sorting breaks after switching from one column to another. For example, if you sort by Crash ID first and then try to sort by Case Number, the query looks like `order_by: {crash_id: asc, case_id: desc}` so sorting breaks for everything except the Crash ID.

The issue is that each new sort selection adds to the GraphQL query but does not remove the previous sort.

![Screen Shot 2019-10-09 at 11 22 42 AM](https://user-images.githubusercontent.com/37249039/66500504-42942380-ea87-11e9-9e9a-e3d9a264f772.png)

**Comment by sergiogcx** [comment]
@mddilley I inadvertently fixed this in a different issue:
https://github.com/cityofaustin/atd-vz-data/pull/267

I vaguely remembered our conversation, so I figured I'd save you the time, I just added two lines of code in order to fix this:

First, in the click handler I added a method to clear all other sort filters:
https://github.com/cityofaustin/atd-vz-data/blob/a50bb99e8e868538f134257deb34d0035b94d766/atd-vze/src/Components/GridTable.js#L68

Secondly, whenever we click the Clear button:
https://github.com/cityofaustin/atd-vz-data/blob/a50bb99e8e868538f134257deb34d0035b94d766/atd-vze/src/Components/GridTable.js#L129

This is the functin in the gqlAbstract.js that does the magic:
https://github.com/cityofaustin/atd-vz-data/blob/a50bb99e8e868538f134257deb34d0035b94d766/atd-vze/src/queries/gqlAbstract.js#L148

**Comment by mddilley** [comment]
Sounds perfect, thanks @sergiogcx!
