### ISSUE TITLE
Crash Details: After editing the fatality flag future edits did not appear to be saved

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-vz-data#313]
After editing the fatality flag, future edits did not appear to be saved (at least, they were not reflected in the UI)

Try editing the fatality flag in this crash:
https://vze-staging.austintexas.io/#/crashes/16871421

**Comment by mateoclarke** [comment]
That makes sense because of the DB triggers. As we discussed IRL, let's make Fatality flag uneditable and move the death count field above it. Seems like the trigger accounts for the change on the death count between 0 and any number >0 and flips the flag accurately. @sergiogcx can you confirm that these triggers are good and updated in prod & staging? Thanks y'all!

**Comment by sergiogcx** [comment]
👍 @mddilley and I made the changes to the trigger in both staging and production. Things should be running based on the limited testing we have done.
