### ISSUE TITLE
VZD: Location index, better sorting logic null values

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#339]
Currently, when you sort the table columns in descending order, where you would expect the highest numbers to be a the top, the null values sort highest.

![Screen Shot 2019-10-21 at 3 47 47 PM](https://user-images.githubusercontent.com/5697474/67242050-4fffc500-f41a-11e9-9681-94252718d65b.png)

**Comment by sergiogcx** [comment]
Just to provide some context as to how the sorting happens:

1. Those numbers are provided through a view: 
2. The view has a location_id
3. We set up a Hasura relationship to associate a location_id from the locations table, to whatever results there are in the view.
4. The view does not include records for all locations, only locations with data.
5. Hasura will not find a relationship for some locations, since the data will not be present coming in from the view.
6. Hasura will sort the data making nulls a higher priority.


Ways to fix this:
1. Generate empty data in the view (with zeroes)
2. Find a way to assume 0 when null through Hasura (not VZE).

**Comment by mateoclarke** [comment]
Sounds like the effort is closer to the database than the GridTable so I changed the issue prefix to VZD.

**Comment by sergiogcx** [comment]
Correct, I don't know why I didn't think of this before, all we needed is a nested query to wrap the output and coalesce the null values :)

Already deployed to production and staging.

PR: 

https://github.com/cityofaustin/atd-vz-data/pull/528
