### ISSUE TITLE
Decided on and implement new VZD routing on Cloudfront

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-vz-data#353]
Today, VZD lives at `vzd.austintexas.io`. We want to move this to our production hosting scheme `austin.gov`, but need to settle on the location. Possibly:

- `vzd.visionzero.austin.gov`
- `visionzero.austin.gov/vzd`
- `api.mobility.austin.gov/vzd`

**Comment by mateoclarke** [comment]
This has been resolved now, we're using `austinmobility.io` domain since this isn't public facing...

Staging:
https://vzd.austinmobility.io/

Production:
https://vzd-staging.austinmobility.io/

I am seeing https://vzd.austintexas.io/ still live. @sergiogcx do we have a plan/issue so we don't forget to turn off or redirect the app instances that live on `austintexas.io`?

**Comment by sergiogcx** [comment]
@mateoclarke "https://vzd.austintexas.io/ " was blocked right after the migration, but since I am doing some testing with ETL I have been using it as a test environment, so for the time being it is enabled again.

I can come up with an HTTP redirect, though not sure what behavior to expect from VZE. I will keep you posted once everything is running as expected.

**Comment by sergiogcx** [comment]
Closing the issue, @mateoclarke answered the issue correctly. There is no further work to be done.
