### ISSUE TITLE
ETL: Write Script to Load CRIS data from SFTP server into VZD

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-vz-data#354]
TxDOT is in the process of providing us a nightly FTP dump to our own AWS SFTP server that @sergiogcx has created. (This is after lots of back and forth between APD and TXDOT both which the strikethrough comments below reference)

They are currently in a testing phase. Once they say they are providing us with accurate/production data, we need to:
- [ ] confirm the extracts have accurate/equivalent data compared to our current import process with Splinter
- [ ] update our ETL scripts move data from the SFTP to our existing AWS infrastructure (S3 bucket of unzipped csv files)
- [ ] retire ETL scripts related to Splinter automated/bot extraction.

**Comment by sergiogcx** [comment]
Lucky does not want to grant us access to `coa22` SFTP server, there APD has their CSV files, so we are meeting with Auzzie, and possibly go back to Lucky and be more specific.

**Comment by mateoclarke** [comment]
Auzzie spoke with her manager and they are no longer on board with us modifying their bash script because of the co-dependency it would create and the liability they feel they would take on if something where to happen with our data stream.

We all agree that setting up a new target SFTP server would be the most sustainable solution. In the meantime, we need to revisit automatting the nightly data extraction with Capybara. 

I'll be responding to our TxDOT contacts with this update.

cc/ @johnclary @sergiogcx

**Comment by mateoclarke** [comment]
I've update the description comment for this issue based on the new info about working with TxDOT and establishing our own nightly data dump via FTP independent from APD. 

This work can be backlogged for now since our current data infrastructure is functional. But it should be prioritized since this will be a more reliable, robust, and an authorized means of integrating VZD with TxDOTs CRIS system in the long-run.
