### ISSUE TITLE
ETL: Create Location Records Polygon Endpoint

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-vz-data#44]
We need a polygon layer of locations (aka, intersections, but trying to get away from that terminology since we need mid-block geometries as well) which will serve as the immutable geometry for aggregating crash data. The data should be (ideally) hosted on AGOL so that we can integrate with REST services and not insane proprietary Esri bs.

**Comment by johnclary** [comment]
Schedule a meeting to discuss with Diana and Jaime tomorrow.

**Comment by johnclary** [comment]
Rescheduled for 7/15.

**Comment by johnclary** [comment]
@jaime-mckeown here's your issue for the research you're doing with Daniel.

**Comment by johnclary** [comment]
@jaime-mckeown any update on this?

**Comment by jaime-mckeown** [comment]
@johnclary Daniel and I talked about it, and he gave me access to his crash diagrams. I haven't gotten to it yet. I saw you had the Issue as On Deck so thought it wasn't as high of a priority. I can start working on it now if need be. Sorry, been super busy this past week.

**Comment by johnclary** [comment]
No problem, we can kick it to sprint 5. Just want to make sure it's on your radar. Did he also share his polygon layer of buffered intersections?

**Comment by jaime-mckeown** [comment]
Ok. Yes, it’s already on my to-do-list. Daniel is using the polygon layer that Cole created.

**Comment by jaime-mckeown** [comment]
Reviewed Daniel's crash analysis reports.

**Comment by jaime-mckeown** [comment]
Looked into how best to separate intersection from mid-block section crashes along street segments. Meeting with Daniel on Thursday to work on specifics for each street level type.

**Comment by johnclary** [comment]
@sergiogcx just updating you that Jaime is working on a dummy polygon endpoint so that you can start working on the issues blocked by this.

**Comment by jaime-mckeown** [comment]
Met with Daniel last Thursday to discuss details for the requirements for creating this polygon layer. He needs cleaner intersections, with no overlap between records in the feature. Streets that cross highways and intersect with frontage roads need to be considered as one intersection. He includes the street up to the first driveway of a commercial center if it occurs before the first intersecting street. Most of the crashes he evaluates happen near highways/frontage roads and on level 3 streets. He's never done a crash analysis on a level 1 or 2 street.

**Comment by jaime-mckeown** [comment]
@sergiogcx The test polygon layer is now on AGOL:

AGOL
https://austin.maps.arcgis.com/home/item.html?id=92cdcff1eb6b47fd83bc847f0ff95f1f

REST Service
https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/Intersection_Polygons_Test/FeatureServer/0?token=3FET3MC8O_5vmD7U0COlpRNembw2UKytz6Gzg95j8pz7AszrPkM8-aZZCFfonx8qTrD8f0pZLt35uDguDrHZA_1l1V-ZhPl5VAoRwSgkpaEsNsvr7wZR_s4jl6cHdx7Vlf7TEOZWI8mbgnqmfj03y1JHO9OOeaXuMbXUD2uwsXcCtODRtydLX6SqSBrQ6an1RJDq1cQLumRnwd1j3PXC31bwL1BiW2jWlIfHjJrypzdUAfrVTns_98gBs6BPa85qpdjxYEtXlSD6IYR39HkF4w..

**Comment by johnclary** [comment]
thanks @jaime-mckeown!

**Comment by jaime-mckeown** [comment]
- Started looking into how we are going to create the layer that is required for more accurate crash report analysis. Starting from scratch will be a huge undertaking, where Cole's intersection polygon layer is good where streets are a uniform grid pattern.
- I spoke to Daniel about starting with Cole's layer and modifying it to suit his needs moving forward. He agreed that it can be used as a starting point, but would need to be fixed, especially along highways/frontage roads. Things to be considered for estimating how long this will take to complete:
----- All highway overpasses where a frontage roads connect to a city street need to be completely modified to suit Daniel's needs.
----- Anywhere that the street layer is not currently covered by the polygon layer will need midpoint polygons created.
----- All other areas where the polygon layer is not clean for intersections will need to be modified.
----- All new streets that have been added to the streets layer since Cole's layer was created will need to be created from scratch.

**Comment by johnclary** [comment]
We talked about this with the VZ team today. Waiting to get their priority on this vs geocoding backlog. Current thinking is:

-    create a hotspot map of high injuries and fatalities locations from most recent five years of CRIS data. Possibly in combination with high-injury network
 - get criteria baseline intersection specification from engineering (e.g. search radius based on road class)
- create a base polygon layer via geoprocessing based on specification
- ideally get 500 location polygons created/QA'd
- continue to develop the polygon dataset over time

**Comment by jaime-mckeown** [comment]
@johnclary are we still waiting to see if Frank is going to work on this? I can get back on it if need be.

**Comment by johnclary** [comment]
@johnclary will talk to Lewis and update y'all.
