### ISSUE TITLE
CRIS+: prototype PostgREST

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#73]
compare as an alternative to Flask-api

- [x] play with views to abstract output
- [x] set up auth

**Comment by sergiogcx** [comment]
Under the current circumstances and time constraints, we are better served using a Flask/Sanic API running on Lambda.

I first tried with AWS Cognito (a serverless authentication service), while it does support symmetric authentication with PostgREST, the configuration necessary to make it work is not the simplest and the use case does not fit our needs. Given that we always have to provide a Client Secret along with the user credentials in order to authenticate, which means there needs to be a middleware (lambda function, or otherwise) that safely stores the secret and returns the token when the user is fully authenticated. This can still be explored if other options aren't as viable.

I also tried with Auth0, the authentication provider PostgREST recommends. They have documentation on how to use them. It was a little easier to set up, and I managed to be able to authenticate. Unfortunately in order to support "AD Connectors" (AD/Office365/SAML/Outlook credentials) you need to pay a steep price for the Developer Pro/Enterprise package. We can still use the free tier to use with PostgREST, but my experience has been that there is a steep learning curve, and troubleshooting takes quite a bit of overhead. 

DevOps is also a challenge, the deployment of the API is not as simple as using Flask/Sanic. So that adds another layer of complexity we need to deal with when troubleshooting, and setting up. Scaling could also become another hurdle to overcome.

Syncing data with other services cannot be implemented with PostgREST. We could use another ETL process externally, and just let PostgREST be an API endpoint. It is important to remember that we will not have a lot of flexibility with PostgREST, and we can only use it as an endpoint.

Closing the issue for now.
