### ISSUE TITLE
VZE: CRIS Record Updates QA Pages (Index, Details)

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#83]
Develop an interface for reviewing CRIS record updates before accepting accepting them (agreed that any change from CRIS to a record that has been modified in VZE will need to be reviewed)

- New CRIS records review page `/crashes/review_new`

How do we resolve conflicts between existing data (that may already be QA'ed) and updates to the same records that we attempt to import from CRIS?

What UI could we provide users to manage the conflicts and decide what columns and records to preserve. How much can we automate via ETL?

**Comment by mateoclarke** [comment]
- QA diff for new CRIS records, comparing changes on certain fields
- prompt the user to accept/reject significant changes to a record
- Postgres: Historic Record table, many updates for one record

**Comment by amenity** [comment]
According to @sergiogcx, we need to decide what columns to evaluate in order to prioritize updates; e.g. a few changes to less important values might be able to go on the back burner. On the other hand, changes to - case ID, people involved, etc. will be more important and probably warrant updates sooner.

**Comment by amenity** [comment]
@mateoclarke @johnclary - remember to propose some of these workflow changes in the 10/3 Sprint Review.

**Comment by mateoclarke** [comment]
Related to #200

**Comment by sergiogcx** [comment]
Comment taken from issue #183

When investigating the behavior of new records coming in from CRIS, we observed that the case number would seldomly change.  It is an important change in the data, since the CR3 narrative and crash diagram depend on it.

We will need to investigate:
- [ ] Are these case numbers changes merely corrections?
- [ ] Are both case numbers the same (just different number)? Is the data (narrative and diagram) the same for both case numbers?
- [ ] Can this change be ignored?
- [ ] Should this change update the narrative?
- [ ] If the narrative changes, possibly the address and lat/longs could change too?

**Comment by sergiogcx** [comment]
The main functionality is basically done, I will need some guidance from stakeholders to know if this is more or less what this is something they can work with:

1. Index Page:

![2019-12-30_12-47-36.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/697c7da4-ed99-4e1a-8bcf-a918ffe27a7a)


2. Diff Viewer:

![2019-12-30_12-55-26.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/c6b3e283-9ab7-4816-a14d-08c58e8a6ee6)

**Comment by sergiogcx** [comment]
The diff viewer will generate the required mutations, all there is left is to execute the mutations through Apollo or Axios, and we are good to go for the UI.

The ETL needs to be fixed, a new issue has been created:

https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-vz-data/578

**Comment by JaceDeloney** [comment]
Taking time to get customer feedback on the progress that has been made. 

Immediate feedback from team:

- Add table headers (e.g., Field Name, Original Record, New Record)
- Move cherrypick selector to far right side of table

**Comment by JaceDeloney** [comment]
We will be review this solution with VZ team next week

**Comment by JaceDeloney** [comment]
Currently the proposal above doesn't include reviews/updates to the units table and persons table. This will cause these two tables to not be updated if changes to the crashes table are made. This was identified from issue #684 

We need to add additional fields in the crash record change review/approval UI so that changes to crash records in CRIS will also be made to the units table and persons table (if the changes are approved). 

If possible, we should consolidate all of the fields from the three tables into a single review pane. VZE users aren't necessarily aware or care that the three tables exist. Their goal is to simply compare and approve the current crash information with the updated crash information.

**Comment by JaceDeloney** [comment]
### Additional requested changes below

**Rename the following:**

- Change "Original" badge to "Current" badge
- Change "Change" badge to "New" badge
- Change "Open Current Record" to "Open Existing Record"
- Change "Download Current CR3" to "Download Existing CR3"
- Change "Discard Incoming Record" to "Discard New Record"

**There should be two CR3s available for download in the details view**
- Download Current CR3
- Download New CR3

Add an "Edited" icon next to current fields that were edited from the original input from the CR3. For example, if a lat/long was edited, the user should be able to know that by seeing the "Edited" icon.

**Comment by JaceDeloney** [comment]
@sergiogcx can you send me the fields that included in the units table and persons table so that we can see which fields overlap between the three tables (crash, units, persons)? This will help us determine what the UI should be to handle review/approval of crash record changes.

**Comment by sergiogcx** [comment]
This is the current list of important fields:

```
CRIS_TXDOT_COMPARE_FIELDS_LIST = [
    "crash_fatal_fl",
    "private_dr_fl",
    "rpt_outside_city_limit_fl",
    "crash_date",
    "crash_time",
    "case_id",
    "rpt_latitude",
    "rpt_longitude",
    "rpt_hwy_num",
    "rpt_block_num",
    "rpt_street_name",
    "rpt_sec_hwy_num",
    "rpt_sec_block_num",
    "rpt_sec_street_name",
    "hwy_nbr",
    "hwy_sys",
    "hwy_sys_2",
    "hwy_nbr_2",
    "city_id",
    "latitude",
    "longitude",
    "street_name",
    "street_nbr",
    "street_name_2",
    "street_nbr_2",
    "sus_serious_injry_cnt",
    "nonincap_injry_cnt",
    "poss_injry_cnt",
    "non_injry_cnt",
    "unkn_injry_cnt",
    "tot_injry_cnt",
    "death_cnt",
]
```
